### ISSUE TITLE
Please provide quantum-blackbird 0.2.4 with test suite

### ISSUE THREAD

**Issue by kevinsmia1939** [XanaduAI/blackbird#27]
Hello,

I am packaging quantum-blackbird 0.2.4 on openSUSE, but I noticed the version 0.2.4 on pypi does not have test suite.
The github release does have test suite, would you mind release 0.2.4 with test?

Thank you very much.

**Comment by josh146** [comment]
Hi @kevinsmia1939, unfortunately the packaging structure we have chosen to use does not package up the tests for PyPI release. however, feel free to use the GitHub release, which does have access to the tests!

**Comment by kevinsmia1939** [comment]
> Hi @kevinsmia1939, unfortunately the packaging structure we have chosen to use does not package up the tests for PyPI release. however, feel free to use the GitHub release, which does have access to the tests!

Hi,

Thanks for reply, but the github release only have version 0.2.1 would you mind release 0.2.4? 
Thanks.
