### ISSUE TITLE
Please provide Blackbird 0.2.4 with test on github to use with Strawberryfield

### ISSUE THREAD

**Issue by kevinsmia1939** [XanaduAI/blackbird#29]
Hello,
I would like to use quantum blackbird with test suite. However, on Github release, I can only download 0.2.1. Which Strawberryfield require at least 0.2.3.

So I would like to request for blackbird 0.2.3 with test or above on Github. Sorry if it came out as pushy, did not mean it.

Thank you.

Relate: #27

**Comment by nquesada** [comment]
Thanks for raising this issue @kevinsmia1939 ! We will be making an updated release shortly.

**Comment by thisac** [comment]
Hi @kevinsmia1939,

There's now a v.0.2.4 release of Blackbird on GitHub, which you can find [here](https://github.com/XanaduAI/blackbird/releases/tag/v0.2.4). This is the same version as the [latest release on PyPI](https://pypi.org/project/quantum-blackbird/), but with the tests included.
